### PR TITLE
feat: update theme

### PR DESCRIPTION
**Pull request by fairlighteth**
# Description

- Updates the Docosaurus theme to reflect the CoW Protocol identity

Screenshot 2023-10-17 at 12 40 31
Screenshot 2023-10-17 at 12 36 10

### CODE REVIEW

**Comment by fairlighteth** [comment]
Some updates to improve swagger styles:
Screenshot 2023-10-17 at 14 46 33
Screenshot 2023-10-17 at 14 46 20
Screenshot 2023-10-17 at 14 46 13

**Comment by fairlighteth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by anxolin — APPROVED** [review]
Great work @fairlighteth

**Review by mfw78 — APPROVED** [review]

**Comment by mfw78** [comment]
recheck

**Pull request merged**
